# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box      = 'centos/7'
  config.vm.hostname = 'webhooks.esri.com'
  config.vm.network 'private_network', type: 'dhcp'
  config.vm.network 'forwarded_port', guest: 5000, host: 5000

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
#	vb.cpus   = '2'
    vb.name   = 'webhooks'
  end

  config.vm.provision 'shell', path: 'provision.sh'
  
end
